#!/usr/bin/env python
"""
EAC Study 2: pretrained-language-model validation with PEFT/LoRA.

Scientific purpose
------------------
This study addresses the main limitation of the synthetic EAC Study 1. It uses
an actual pretrained causal language model, freezes its base weights, learns an
initial task adapter from externally observed demonstrations, then ends the
external-observation phase. During the endogenous phase, novel candidate
problems are generated by an internal scheduler from already-seen symbol
vocabulary. The model proposes candidate answers. A deterministic executable
verifier returns pass/fail only; it never inserts a corrected answer when the
model failed to generate it. Accepted internally generated examples can then be
consolidated through LoRA.

Primary conditions
------------------
no_update                no endogenous update
replay                    literal replay of observed demonstrations
unchecked                 self-training on the model's own pseudo-labels
validated                 uniform endogenous recombination + executable verifier
hard_validated            uncertainty-targeted endogenous practice + verifier
dream_validated           cross-context recombination + verifier
hard_validated_anchor     hard_validated plus old-task anchor replay

Primary hypotheses are frozen in STUDY2_CONFIRMATORY_PROTOCOL.md.

The task is deliberately small enough for a laptop. It is still synthetic at the
problem level, but unlike Study 1 the learner is a pretrained Transformer with
real PEFT/LoRA attention-layer updates. Results therefore address model-scale
construct validity, not ecological validity on open-ended language tasks.
"""

import argparse
import copy
import gc
import json
import math
import os
import random
import time
from dataclasses import dataclass, asdict
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
from scipy import stats

try:
    import torch
    import torch.nn.functional as F
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import (
        LoraConfig,
        TaskType,
        get_peft_model,
        get_peft_model_state_dict,
        set_peft_model_state_dict,
    )
except Exception as exc:  # pragma: no cover
    torch = None
    _IMPORT_ERROR = exc
else:
    _IMPORT_ERROR = None


# ----------------------------- statistics ---------------------------------

def holm_adjust(pvals):
    pvals = np.asarray(pvals, dtype=float)
    m = len(pvals)
    order = np.argsort(pvals)
    out = np.empty(m)
    running = 0.0
    for rank, idx in enumerate(order):
        adj = (m - rank) * pvals[idx]
        running = max(running, adj)
        out[idx] = min(1.0, running)
    return out


def paired_stats(a, b, alternative="greater"):
    a = np.asarray(a, float)
    b = np.asarray(b, float)
    d = a - b
    n = len(d)
    mean = float(np.mean(d))
    sd = float(np.std(d, ddof=1)) if n > 1 else float("nan")
    se = sd / math.sqrt(n) if n > 1 and sd > 0 else 0.0
    if n > 1 and sd > 0:
        tcrit = stats.t.ppf(0.975, n - 1)
        ci = (mean - tcrit * se, mean + tcrit * se)
        t = mean / se
        p2 = 2 * stats.t.sf(abs(t), n - 1)
        if alternative == "greater":
            p = p2 / 2 if t >= 0 else 1 - p2 / 2
        elif alternative == "less":
            p = p2 / 2 if t <= 0 else 1 - p2 / 2
        else:
            p = p2
        dz = mean / sd
    else:
        ci = (mean, mean)
        t = float("inf") if mean > 0 else (-float("inf") if mean < 0 else 0.0)
        p = 0.0 if mean > 0 and alternative == "greater" else 1.0
        dz = float("inf") if mean > 0 else 0.0
    try:
        w = stats.wilcoxon(d, alternative=alternative, zero_method="wilcox")
        pw = float(w.pvalue)
    except Exception:
        pw = float("nan")
    nonzero = d[d != 0]
    if len(nonzero):
        signp = float(stats.binomtest(int(np.sum(nonzero > 0)), len(nonzero), .5,
                                     alternative=alternative).pvalue)
    else:
        signp = 1.0
    return {
        "n": n,
        "mean_diff": mean,
        "ci_low": ci[0],
        "ci_high": ci[1],
        "t": float(t),
        "p_one_sided": float(p),
        "cohen_dz": float(dz),
        "wilcoxon_p": pw,
        "sign_test_p": signp,
        "wins": int(np.sum(d > 0)),
        "ties": int(np.sum(d == 0)),
        "losses": int(np.sum(d < 0)),
    }


# ------------------------------ config ------------------------------------

@dataclass
class Config:
    model_name: str = "HuggingFaceTB/SmolLM2-135M-Instruct"
    seeds: int = 12
    base_seed: int = 41001
    seed_stride: int = 97
    domain_n: int = 20
    n_classes: int = 4
    target_exposure_n: int = 56
    anchor_exposure_n: int = 48
    target_eval_cross_n: int = 80
    target_eval_same_n: int = 40
    anchor_eval_n: int = 100
    internal_prompt_budget: int = 96
    candidate_samples: int = 5
    initial_steps: int = 70
    adapt_steps: int = 28
    batch_size: int = 8
    learning_rate_initial: float = 2.5e-3
    learning_rate_adapt: float = 1.6e-3
    lora_rank: int = 4
    lora_alpha: int = 8
    lora_dropout: float = 0.0
    max_length: int = 56
    hard_pool_multiplier: int = 2
    anchor_fraction: float = 0.25
    temperature: float = 1.15
    device: str = "cpu"
    torch_threads: int = 0


def preset(name: str) -> Config:
    if name == "smoke":
        return Config(
            model_name="HuggingFaceTB/SmolLM2-135M-Instruct",
            seeds=1,
            target_exposure_n=20,
            anchor_exposure_n=16,
            target_eval_cross_n=12,
            target_eval_same_n=8,
            anchor_eval_n=16,
            internal_prompt_budget=16,
            candidate_samples=3,
            initial_steps=4,
            adapt_steps=3,
            batch_size=4,
        )
    if name == "pilot":
        return Config(
            model_name="HuggingFaceTB/SmolLM2-135M-Instruct",
            seeds=3,
            initial_steps=35,
            adapt_steps=14,
            internal_prompt_budget=48,
        )
    if name == "confirmatory":
        # Frozen paper-primary configuration. Do not alter after inspecting outcomes.
        return Config()
    if name == "replication360":
        # Independent larger-model replication; run only with a fresh output folder.
        return Config(
            model_name="HuggingFaceTB/SmolLM2-360M-Instruct",
            seeds=8,
            base_seed=61001,
            seed_stride=101,
            initial_steps=70,
            adapt_steps=28,
        )
    raise ValueError(f"Unknown preset: {name}")


# -------------------------- deterministic task ----------------------------

LABEL_NAMES = ["A", "B", "C", "D"]


def set_all_seeds(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    if torch is not None:
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)


def rule_params(rng: np.random.Generator):
    # Coefficients are intentionally small and nonzero. The task name is arbitrary,
    # so pretraining cannot know the per-seed mapping in advance.
    a = int(rng.choice([1, 2, 3]))
    b = int(rng.choice([1, 2, 3]))
    c = int(rng.integers(0, 4))
    return (a, b, c)


def apply_rule(pair: Tuple[int, int], params: Tuple[int, int, int], n_classes=4):
    x, y = pair
    a, b, c = params
    return int((a * x + b * y + c) % n_classes)


def same_context(pair: Tuple[int, int], domain_n: int):
    x, y = pair
    half = domain_n // 2
    return (x < half and y < half) or (x >= half and y >= half)


def split_pairs(seed: int, cfg: Config):
    rr = np.random.default_rng(seed)
    all_pairs = [(i, j) for i in range(cfg.domain_n) for j in range(cfg.domain_n)]
    same = [p for p in all_pairs if same_context(p, cfg.domain_n)]
    cross = [p for p in all_pairs if not same_context(p, cfg.domain_n)]
    rr.shuffle(same)
    rr.shuffle(cross)

    target_exposure = same[:cfg.target_exposure_n]
    same_rest = same[cfg.target_exposure_n:]
    target_eval_same = same_rest[:cfg.target_eval_same_n]
    same_rest = same_rest[cfg.target_eval_same_n:]
    target_eval_cross = cross[:cfg.target_eval_cross_n]
    cross_rest = cross[cfg.target_eval_cross_n:]

    eval_set = set(target_eval_same + target_eval_cross)
    exposure_set = set(target_exposure)
    internal_uniform = [p for p in all_pairs if p not in eval_set and p not in exposure_set]
    rr.shuffle(internal_uniform)
    dream_cross = [p for p in cross_rest if p not in exposure_set]
    rr.shuffle(dream_cross)

    anchor_all = all_pairs.copy()
    rr.shuffle(anchor_all)
    anchor_exposure = anchor_all[:cfg.anchor_exposure_n]
    anchor_eval = anchor_all[cfg.anchor_exposure_n:cfg.anchor_exposure_n + cfg.anchor_eval_n]

    return {
        "target_exposure": target_exposure,
        "target_eval_same": target_eval_same,
        "target_eval_cross": target_eval_cross,
        "target_eval_all": target_eval_same + target_eval_cross,
        "internal_uniform": internal_uniform,
        "dream_cross": dream_cross,
        "anchor_exposure": anchor_exposure,
        "anchor_eval": anchor_eval,
    }


def make_prompt(task: str, pair: Tuple[int, int]):
    x, y = pair
    return (
        f"Hidden-rule task {task}. first={x}; second={y}. "
        "Return exactly one class label from A, B, C, or D. Class:"
    )


def examples(task: str, pairs, params, n_classes=4):
    return [(make_prompt(task, p), apply_rule(p, params, n_classes), p) for p in pairs]


# -------------------------- model / tokenizer ------------------------------


def require_dependencies():
    if torch is None:
        raise RuntimeError(
            "PyTorch/Transformers/PEFT import failed. Install requirements first. "
            f"Original import error: {_IMPORT_ERROR}"
        )


def label_token_ids(tokenizer):
    # Prefer whitespace-prefixed single tokens because prompts end at 'Class:'.
    ids = []
    target_text = []
    for label in LABEL_NAMES:
        choices = [f" {label}", label]
        found = None
        for txt in choices:
            enc = tokenizer.encode(txt, add_special_tokens=False)
            if len(enc) == 1:
                found = (enc[0], txt)
                break
        if found is None:
            raise RuntimeError(
                f"Could not find a single-token encoding for class {label}. "
                "Try a different model/tokenizer."
            )
        ids.append(found[0])
        target_text.append(found[1])
    if len(set(ids)) != len(ids):
        raise RuntimeError(f"Class token IDs are not distinct: {ids}")
    return ids, target_text


def infer_lora_targets(model):
    leaves = {name.split(".")[-1] for name, _ in model.named_modules()}
    if {"q_proj", "v_proj"}.issubset(leaves):
        return ["q_proj", "v_proj"]
    if "c_attn" in leaves:  # GPT-2 family
        return ["c_attn"]
    if {"query", "value"}.issubset(leaves):
        return ["query", "value"]
    # Last-resort common projection names.
    candidates = [x for x in ["q_proj", "v_proj", "k_proj", "o_proj"] if x in leaves]
    if candidates:
        return candidates[:2]
    raise RuntimeError(
        "Could not infer LoRA target modules. Inspect model.named_modules() and "
        "supply a supported model."
    )


def load_model(cfg: Config, seed: int):
    set_all_seeds(seed)
    tokenizer = AutoTokenizer.from_pretrained(cfg.model_name)
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token
    model = AutoModelForCausalLM.from_pretrained(cfg.model_name)
    targets = infer_lora_targets(model)
    lcfg = LoraConfig(
        r=cfg.lora_rank,
        lora_alpha=cfg.lora_alpha,
        lora_dropout=cfg.lora_dropout,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
        target_modules=targets,
    )
    model = get_peft_model(model, lcfg)
    model.to(cfg.device)
    model.train()
    return model, tokenizer, targets


def adapter_snapshot(model):
    state = get_peft_model_state_dict(model)
    return {k: v.detach().cpu().clone() for k, v in state.items()}


def restore_adapter(model, state):
    set_peft_model_state_dict(model, {k: v.to(model.device) for k, v in state.items()})


def trainable_parameter_count(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)


def adapter_l2(model):
    total = 0.0
    for p in model.parameters():
        if p.requires_grad:
            total += float((p.detach().float().cpu() ** 2).sum())
    return math.sqrt(total)


# ----------------------------- batching -----------------------------------


def build_batch(tokenizer, label_ids, batch, max_length, device):
    sequences = []
    labels = []
    for prompt, y, _pair in batch:
        pids = tokenizer.encode(prompt, add_special_tokens=True)
        pids = pids[-(max_length - 1):]
        seq = pids + [int(label_ids[y])]
        lab = [-100] * len(pids) + [int(label_ids[y])]
        sequences.append(seq)
        labels.append(lab)
    maxlen = max(len(s) for s in sequences)
    pad = tokenizer.pad_token_id
    input_ids = []
    attention = []
    label_mat = []
    for seq, lab in zip(sequences, labels):
        n = maxlen - len(seq)
        input_ids.append(seq + [pad] * n)
        attention.append([1] * len(seq) + [0] * n)
        label_mat.append(lab + [-100] * n)
    return {
        "input_ids": torch.tensor(input_ids, dtype=torch.long, device=device),
        "attention_mask": torch.tensor(attention, dtype=torch.long, device=device),
        "labels": torch.tensor(label_mat, dtype=torch.long, device=device),
    }


def train_steps(model, tokenizer, label_ids, dataset, steps, batch_size, lr,
                max_length, device, seed):
    if not dataset or steps <= 0:
        return 0.0
    rr = np.random.default_rng(seed)
    model.train()
    opt = torch.optim.AdamW([p for p in model.parameters() if p.requires_grad], lr=lr)
    started = time.perf_counter()
    for _ in range(steps):
        idx = rr.integers(0, len(dataset), size=batch_size)
        batch = [dataset[int(i)] for i in idx]
        tensors = build_batch(tokenizer, label_ids, batch, max_length, device)
        out = model(**tensors)
        loss = out.loss
        opt.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_([p for p in model.parameters() if p.requires_grad], 1.0)
        opt.step()
    return time.perf_counter() - started


@torch.no_grad()
def class_probabilities(model, tokenizer, label_ids, prompts, max_length, device, batch_size=16):
    model.eval()
    all_probs = []
    for start in range(0, len(prompts), batch_size):
        chunk = prompts[start:start + batch_size]
        toks = [tokenizer.encode(p, add_special_tokens=True)[-(max_length):] for p in chunk]
        maxlen = max(len(x) for x in toks)
        pad = tokenizer.pad_token_id
        ids = [x + [pad] * (maxlen - len(x)) for x in toks]
        att = [[1] * len(x) + [0] * (maxlen - len(x)) for x in toks]
        input_ids = torch.tensor(ids, dtype=torch.long, device=device)
        attention = torch.tensor(att, dtype=torch.long, device=device)
        out = model(input_ids=input_ids, attention_mask=attention)
        lengths = attention.sum(1) - 1
        rows = torch.arange(len(chunk), device=device)
        next_logits = out.logits[rows, lengths]
        class_logits = next_logits[:, torch.tensor(label_ids, device=device)]
        probs = torch.softmax(class_logits.float(), dim=-1)
        all_probs.append(probs.cpu())
    return torch.cat(all_probs, dim=0).numpy()


def ece_score(probs, y, bins=10):
    probs = np.asarray(probs)
    y = np.asarray(y)
    pred = probs.argmax(1)
    conf = probs.max(1)
    correct = (pred == y).astype(float)
    ece = 0.0
    edges = np.linspace(0, 1, bins + 1)
    for lo, hi in zip(edges[:-1], edges[1:]):
        mask = (conf >= lo) & (conf < hi if hi < 1 else conf <= hi)
        if mask.any():
            ece += mask.mean() * abs(correct[mask].mean() - conf[mask].mean())
    return float(ece)


def evaluate(model, tokenizer, label_ids, dataset, cfg):
    prompts = [x[0] for x in dataset]
    y = np.array([x[1] for x in dataset], dtype=int)
    probs = class_probabilities(model, tokenizer, label_ids, prompts,
                                cfg.max_length, cfg.device, cfg.batch_size * 2)
    pred = probs.argmax(1)
    acc = float((pred == y).mean()) if len(y) else float("nan")
    nll = float(-np.log(np.clip(probs[np.arange(len(y)), y], 1e-9, 1)).mean()) if len(y) else float("nan")
    return {
        "accuracy": acc,
        "nll": nll,
        "ece": ece_score(probs, y) if len(y) else float("nan"),
        "mean_confidence": float(probs.max(1).mean()) if len(y) else float("nan"),
    }


# ---------------------- endogenous data generation ------------------------


def sample_from_probs(probs, k, temperature, rr):
    p = np.asarray(probs, float)
    logits = np.log(np.clip(p, 1e-12, 1)) / max(temperature, 1e-6)
    q = np.exp(logits - logits.max())
    q /= q.sum()
    return rr.choice(len(q), size=k, replace=True, p=q)


def make_unchecked_dataset(model, tokenizer, label_ids, pool_examples, cfg, seed):
    rr = np.random.default_rng(seed)
    chosen = pool_examples.copy()
    rr.shuffle(chosen)
    chosen = chosen[:cfg.internal_prompt_budget]
    probs = class_probabilities(model, tokenizer, label_ids, [e[0] for e in chosen],
                                cfg.max_length, cfg.device, cfg.batch_size * 2)
    out = []
    wrong = 0
    for e, p in zip(chosen, probs):
        candidates = sample_from_probs(p, cfg.candidate_samples, cfg.temperature, rr)
        # No verifier: choose the most frequent internally sampled class, tie broken by model probability.
        counts = np.bincount(candidates, minlength=cfg.n_classes)
        best = np.flatnonzero(counts == counts.max())
        yhat = int(best[np.argmax(p[best])])
        if yhat != e[1]:
            wrong += 1
        out.append((e[0], yhat, e[2]))
    return out, {
        "generated_prompts": len(chosen),
        "accepted": len(out),
        "acceptance_rate": 1.0,
        "pseudo_label_error_rate": wrong / max(1, len(out)),
    }


def validated_dataset(model, tokenizer, label_ids, pool_examples, cfg, seed,
                      hard=False):
    rr = np.random.default_rng(seed)
    pool = pool_examples.copy()
    if hard:
        score_n = min(len(pool), cfg.internal_prompt_budget * cfg.hard_pool_multiplier)
        rr.shuffle(pool)
        candidate_pool = pool[:score_n]
        probs0 = class_probabilities(model, tokenizer, label_ids, [e[0] for e in candidate_pool],
                                     cfg.max_length, cfg.device, cfg.batch_size * 2)
        entropy = -(probs0 * np.log(np.clip(probs0, 1e-12, 1))).sum(1)
        order = np.argsort(-entropy)
        chosen = [candidate_pool[int(i)] for i in order[:cfg.internal_prompt_budget]]
        probs = probs0[order[:cfg.internal_prompt_budget]]
    else:
        rr.shuffle(pool)
        chosen = pool[:cfg.internal_prompt_budget]
        probs = class_probabilities(model, tokenizer, label_ids, [e[0] for e in chosen],
                                    cfg.max_length, cfg.device, cfg.batch_size * 2)

    accepted = []
    attempts = 0
    for e, p in zip(chosen, probs):
        candidates = sample_from_probs(p, cfg.candidate_samples, cfg.temperature, rr)
        attempts += len(candidates)
        # Executable verifier returns pass/fail. It does NOT supply a corrected label if all candidates fail.
        good = [int(c) for c in candidates if int(c) == int(e[1])]
        if good:
            accepted.append((e[0], good[0], e[2]))
    return accepted, {
        "generated_prompts": len(chosen),
        "candidate_attempts": attempts,
        "accepted": len(accepted),
        "acceptance_rate": len(accepted) / max(1, len(chosen)),
        "pseudo_label_error_rate": 0.0,
    }


def mix_anchor(endogenous, anchors, fraction, total_size, seed):
    rr = np.random.default_rng(seed)
    n_anchor = int(round(total_size * fraction))
    n_endo = max(0, total_size - n_anchor)
    out = []
    if endogenous:
        out.extend([endogenous[int(i)] for i in rr.integers(0, len(endogenous), size=n_endo)])
    if anchors:
        out.extend([anchors[int(i)] for i in rr.integers(0, len(anchors), size=n_anchor)])
    rr.shuffle(out)
    return out


# ---------------------------- one seed ------------------------------------

CONDITIONS = [
    "no_update",
    "replay",
    "unchecked",
    "validated",
    "hard_validated",
    "dream_validated",
    "hard_validated_anchor",
]


def run_seed(seed: int, cfg: Config):
    require_dependencies()
    set_all_seeds(seed)
    rr = np.random.default_rng(seed)
    splits = split_pairs(seed, cfg)
    target_rule = rule_params(rr)
    anchor_rule = rule_params(rr)
    while anchor_rule == target_rule:
        anchor_rule = rule_params(rr)

    target_exp = examples("ZORP", splits["target_exposure"], target_rule, cfg.n_classes)
    target_eval_all = examples("ZORP", splits["target_eval_all"], target_rule, cfg.n_classes)
    target_eval_cross = examples("ZORP", splits["target_eval_cross"], target_rule, cfg.n_classes)
    target_eval_same = examples("ZORP", splits["target_eval_same"], target_rule, cfg.n_classes)
    uniform_pool = examples("ZORP", splits["internal_uniform"], target_rule, cfg.n_classes)
    dream_pool = examples("ZORP", splits["dream_cross"], target_rule, cfg.n_classes)
    anchor_exp = examples("MIRA", splits["anchor_exposure"], anchor_rule, cfg.n_classes)
    anchor_eval = examples("MIRA", splits["anchor_eval"], anchor_rule, cfg.n_classes)

    model, tokenizer, targets = load_model(cfg, seed)
    label_ids, label_text = label_token_ids(tokenizer)

    # Initial external-observation phase. This is the only phase that receives externally stored labels.
    initial_data = target_exp + anchor_exp
    initial_seconds = train_steps(
        model, tokenizer, label_ids, initial_data, cfg.initial_steps, cfg.batch_size,
        cfg.learning_rate_initial, cfg.max_length, cfg.device, seed + 1
    )
    init_state = adapter_snapshot(model)
    baseline_target = evaluate(model, tokenizer, label_ids, target_eval_all, cfg)
    baseline_cross = evaluate(model, tokenizer, label_ids, target_eval_cross, cfg)
    baseline_same = evaluate(model, tokenizer, label_ids, target_eval_same, cfg)
    baseline_anchor = evaluate(model, tokenizer, label_ids, anchor_eval, cfg)

    # Freeze endogenous datasets from exactly the same post-exposure model state.
    unchecked_data, unchecked_meta = make_unchecked_dataset(
        model, tokenizer, label_ids, uniform_pool, cfg, seed + 11
    )
    validated_data, validated_meta = validated_dataset(
        model, tokenizer, label_ids, uniform_pool, cfg, seed + 12, hard=False
    )
    hard_data, hard_meta = validated_dataset(
        model, tokenizer, label_ids, uniform_pool, cfg, seed + 13, hard=True
    )
    dream_data, dream_meta = validated_dataset(
        model, tokenizer, label_ids, dream_pool, cfg, seed + 14, hard=False
    )

    generation_meta = {
        "unchecked": unchecked_meta,
        "validated": validated_meta,
        "hard_validated": hard_meta,
        "dream_validated": dream_meta,
    }

    rows = []
    for cidx, condition in enumerate(CONDITIONS):
        restore_adapter(model, init_state)
        adapt_seconds = 0.0
        train_data = []
        meta = {"generated_prompts": 0, "accepted": 0, "acceptance_rate": 0.0,
                "pseudo_label_error_rate": 0.0}

        if condition == "no_update":
            pass
        elif condition == "replay":
            train_data = target_exp
            meta = {"generated_prompts": len(target_exp), "accepted": len(target_exp),
                    "acceptance_rate": 1.0, "pseudo_label_error_rate": 0.0}
        elif condition == "unchecked":
            train_data = unchecked_data
            meta = unchecked_meta
        elif condition == "validated":
            train_data = validated_data
            meta = validated_meta
        elif condition == "hard_validated":
            train_data = hard_data
            meta = hard_meta
        elif condition == "dream_validated":
            train_data = dream_data
            meta = dream_meta
        elif condition == "hard_validated_anchor":
            # Same hard endogenous examples as hard_validated; only consolidation mix differs.
            total = max(cfg.batch_size, max(1, len(hard_data)))
            train_data = mix_anchor(hard_data, anchor_exp, cfg.anchor_fraction,
                                    total, seed + 900)
            meta = dict(hard_meta)
        else:
            raise ValueError(condition)

        if condition != "no_update" and train_data:
            adapt_seconds = train_steps(
                model, tokenizer, label_ids, train_data, cfg.adapt_steps, cfg.batch_size,
                cfg.learning_rate_adapt, cfg.max_length, cfg.device,
                seed + 1000 + cidx
            )

        m_all = evaluate(model, tokenizer, label_ids, target_eval_all, cfg)
        m_cross = evaluate(model, tokenizer, label_ids, target_eval_cross, cfg)
        m_same = evaluate(model, tokenizer, label_ids, target_eval_same, cfg)
        m_anchor = evaluate(model, tokenizer, label_ids, anchor_eval, cfg)

        rows.append({
            "seed": seed,
            "condition": condition,
            "model_name": cfg.model_name,
            "target_rule": str(target_rule),
            "anchor_rule": str(anchor_rule),
            "target_accuracy": m_all["accuracy"],
            "target_cross_accuracy": m_cross["accuracy"],
            "target_same_accuracy": m_same["accuracy"],
            "target_nll": m_all["nll"],
            "target_ece": m_all["ece"],
            "target_confidence": m_all["mean_confidence"],
            "anchor_accuracy": m_anchor["accuracy"],
            "anchor_nll": m_anchor["nll"],
            "baseline_target_accuracy": baseline_target["accuracy"],
            "baseline_cross_accuracy": baseline_cross["accuracy"],
            "baseline_same_accuracy": baseline_same["accuracy"],
            "baseline_anchor_accuracy": baseline_anchor["accuracy"],
            "generated_prompts": int(meta.get("generated_prompts", 0)),
            "candidate_attempts": int(meta.get("candidate_attempts", 0)),
            "accepted": int(meta.get("accepted", 0)),
            "acceptance_rate": float(meta.get("acceptance_rate", 0.0)),
            "pseudo_label_error_rate": float(meta.get("pseudo_label_error_rate", 0.0)),
            "initial_train_seconds": initial_seconds,
            "adapt_seconds": adapt_seconds,
            "adapter_l2": adapter_l2(model),
            "trainable_parameters": trainable_parameter_count(model),
            "lora_targets": ",".join(targets),
            "label_tokens": json.dumps(label_text),
        })

    # Free large objects between seeds.
    del model
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    return rows


# --------------------------- hypothesis tests ------------------------------

PRIMARY = [
    # name, treatment, control, metric, interpretation
    ("R1_validated_gt_replay", "validated", "replay", "target_accuracy",
     "Validated endogenous adaptation improves held-out target accuracy beyond literal replay."),
    ("R2_validated_gt_unchecked", "validated", "unchecked", "target_accuracy",
     "Executable validation improves endogenous adaptation over unchecked self-training."),
    ("R3_hard_gt_uniform", "hard_validated", "validated", "target_accuracy",
     "Uncertainty-targeted endogenous practice improves held-out accuracy over uniform validated practice."),
    ("R4_dream_gt_replay_cross", "dream_validated", "replay", "target_cross_accuracy",
     "Validated cross-context recombination improves withheld cross-context accuracy over replay."),
    ("R5_anchor_preservation", "hard_validated_anchor", "hard_validated", "anchor_accuracy",
     "Anchor replay preserves prior-task accuracy during endogenous adaptation."),
]


def hypothesis_table(df: pd.DataFrame):
    rows = []
    for name, treat, control, metric, claim in PRIMARY:
        pivot = df.pivot(index="seed", columns="condition", values=metric)
        a = pivot[treat].to_numpy()
        b = pivot[control].to_numpy()
        st = paired_stats(a, b, "greater")
        rows.append({
            "hypothesis": name,
            "claim": claim,
            "metric": metric,
            "treatment_condition": treat,
            "control_condition": control,
            "treatment_mean": float(np.mean(a)),
            "control_mean": float(np.mean(b)),
            **st,
        })
    out = pd.DataFrame(rows)
    out["holm_p"] = holm_adjust(out["p_one_sided"].to_numpy())
    out["reject_h0_0.05"] = out["holm_p"] < .05
    return out


# ------------------------------- plots ------------------------------------

def make_plots(df: pd.DataFrame, tests: pd.DataFrame, out_dir: str):
    import matplotlib.pyplot as plt
    pdir = os.path.join(out_dir, "plots")
    os.makedirs(pdir, exist_ok=True)

    order = CONDITIONS
    means = df.groupby("condition")["target_accuracy"].mean().reindex(order)
    fig, ax = plt.subplots(figsize=(10, 5.5))
    ax.bar(np.arange(len(order)), means.values)
    ax.set_xticks(np.arange(len(order)))
    ax.set_xticklabels(order, rotation=35, ha="right")
    ax.set_ylabel("Held-out target accuracy")
    ax.set_title("Study 2: held-out target accuracy by condition")
    fig.tight_layout()
    fig.savefig(os.path.join(pdir, "01_condition_target_accuracy.png"), dpi=180)
    plt.close(fig)

    y = np.arange(len(tests))
    diff = tests["mean_diff"].to_numpy()
    lo = diff - tests["ci_low"].to_numpy()
    hi = tests["ci_high"].to_numpy() - diff
    fig, ax = plt.subplots(figsize=(9, 5.5))
    ax.errorbar(diff, y, xerr=np.vstack([lo, hi]), fmt="o", capsize=4)
    ax.axvline(0, linewidth=1)
    ax.set_yticks(y)
    ax.set_yticklabels(tests["hypothesis"])
    ax.set_xlabel("Treatment - control")
    ax.set_title("Primary paired effects with 95% confidence intervals")
    fig.tight_layout()
    fig.savefig(os.path.join(pdir, "02_primary_effects_95ci.png"), dpi=180)
    plt.close(fig)

    anchor = df.groupby("condition")["anchor_accuracy"].mean().reindex(order)
    fig, ax = plt.subplots(figsize=(10, 5.5))
    ax.bar(np.arange(len(order)), anchor.values)
    ax.set_xticks(np.arange(len(order)))
    ax.set_xticklabels(order, rotation=35, ha="right")
    ax.set_ylabel("Anchor-task accuracy")
    ax.set_title("Prior-task retention by condition")
    fig.tight_layout()
    fig.savefig(os.path.join(pdir, "03_anchor_retention.png"), dpi=180)
    plt.close(fig)

    acc = df[df["condition"].isin(["unchecked", "validated", "hard_validated", "dream_validated"])]
    accm = acc.groupby("condition")["acceptance_rate"].mean()
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.bar(np.arange(len(accm)), accm.values)
    ax.set_xticks(np.arange(len(accm)))
    ax.set_xticklabels(accm.index, rotation=25, ha="right")
    ax.set_ylabel("Accepted prompts / generated prompts")
    ax.set_title("Endogenous candidate acceptance")
    fig.tight_layout()
    fig.savefig(os.path.join(pdir, "04_acceptance_rates.png"), dpi=180)
    plt.close(fig)

    # Per-hypothesis paired seed plots.
    for i, (name, treat, control, metric, _claim) in enumerate(PRIMARY, start=5):
        pivot = df.pivot(index="seed", columns="condition", values=metric).sort_index()
        x = np.arange(len(pivot))
        fig, ax = plt.subplots(figsize=(8.5, 4.7))
        ax.plot(x, pivot[treat].to_numpy(), marker="o", label=treat)
        ax.plot(x, pivot[control].to_numpy(), marker="o", label=control)
        ax.set_xlabel("Matched seed index")
        ax.set_ylabel(metric)
        ax.set_title(name)
        ax.legend()
        fig.tight_layout()
        fig.savefig(os.path.join(pdir, f"{i:02d}_{name}.png"), dpi=170)
        plt.close(fig)


# ------------------------------ runner ------------------------------------

def write_summary(df, tests, cfg, out_dir):
    lines = []
    lines.append("EAC STUDY 2 - PRETRAINED LM + LORA")
    lines.append("=" * 50)
    lines.append(json.dumps(asdict(cfg), indent=2))
    lines.append("")
    lines.append("PRIMARY HYPOTHESES")
    for _, r in tests.iterrows():
        lines.append(
            f"{r['hypothesis']}: treatment={r['treatment_mean']:.4f}, "
            f"control={r['control_mean']:.4f}, diff={r['mean_diff']:.4f}, "
            f"95%CI=[{r['ci_low']:.4f},{r['ci_high']:.4f}], "
            f"p={r['p_one_sided']:.3e}, Holm={r['holm_p']:.3e}, "
            f"wins/ties/losses={int(r['wins'])}/{int(r['ties'])}/{int(r['losses'])}, "
            f"decision={'REJECT H0' if r['reject_h0_0.05'] else 'FAIL TO REJECT H0'}"
        )
    lines.append("")
    lines.append("IMPORTANT INTERPRETATION")
    lines.append("- The external-observation phase ends before endogenous candidate generation.")
    lines.append("- Programmatic verifier feedback is evaluative information; this study is NOT information-free learning.")
    lines.append("- The verifier gives pass/fail only. If the model never samples the correct class, no corrected label is inserted.")
    lines.append("- The task is synthetic, but the learner is a real pretrained causal Transformer with frozen base weights and PEFT/LoRA updates.")
    lines.append("- Do not tune the confirmatory preset after inspecting these results. Use the replication360 preset with fresh seeds for a larger-model replication.")
    with open(os.path.join(out_dir, "SUMMARY.txt"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def run(cfg: Config, output: str):
    require_dependencies()
    os.makedirs(output, exist_ok=True)
    if cfg.torch_threads and cfg.torch_threads > 0:
        torch.set_num_threads(cfg.torch_threads)
    with open(os.path.join(output, "run_config.json"), "w", encoding="utf-8") as f:
        json.dump(asdict(cfg), f, indent=2)

    all_rows = []
    seeds = [cfg.base_seed + cfg.seed_stride * i for i in range(cfg.seeds)]
    for i, seed in enumerate(seeds, start=1):
        print(f"[{i}/{len(seeds)}] seed={seed} model={cfg.model_name}", flush=True)
        rows = run_seed(seed, cfg)
        all_rows.extend(rows)
        pd.DataFrame(all_rows).to_csv(os.path.join(output, "metrics_partial.csv"), index=False)

    df = pd.DataFrame(all_rows)
    df.to_csv(os.path.join(output, "metrics.csv"), index=False)
    tests = hypothesis_table(df)
    tests.to_csv(os.path.join(output, "hypothesis_tests.csv"), index=False)
    make_plots(df, tests, output)
    write_summary(df, tests, cfg, output)
    print("Done. Results written to", output)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--preset", choices=["smoke", "pilot", "confirmatory", "replication360"], default="smoke")
    p.add_argument("--output", default="eac_reallm_smoke")
    p.add_argument("--model", default=None, help="Override model name. Do not override for the frozen confirmatory run.")
    p.add_argument("--device", choices=["cpu", "cuda"], default=None)
    p.add_argument("--torch-threads", type=int, default=None)
    args = p.parse_args()
    cfg = preset(args.preset)
    if args.model:
        cfg.model_name = args.model
    if args.device:
        cfg.device = args.device
    if args.torch_threads is not None:
        cfg.torch_threads = args.torch_threads
    run(cfg, args.output)


if __name__ == "__main__":
    main()
